[package]
authors = ["Mahdi Robatipoor <mahdi.robatipoor@gmail.com>"]
edition = "2018"
name = "file-center"
version = "0.1.0"

[dependencies]
actix-cors = "0.2.0"
actix-rt = "1.0"
actix-service = "1.0.5"
actix-web = "2.0"
bcrypt = "0.6.3"
dotenv = "0.15.0"
env_logger = "0.7.1"
futures = "0.3.4"
jsonwebtoken = "7"
log = "0.4.8"
serde_json = "1.0.50"
chrono = "0.4.11"
derive-new = "0.5"
actix-multipart = "0.2.0"
actix-files = "0.2.1"
anyhow = "1.0"
strum = "0.18.0"
strum_macros = "0.18.0"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.8"

[dependencies.sqlx]
features = ["runtime-tokio", "sqlite", "macros"]
default-features = false
version = "0.3.3"

[dependencies.serde]
features = ["derive"]
version = "1.0"
